format_version = 2

[apps.SwiftASWFDemo]
identifier = 'io.athem.SwiftASWFDemo'
product = 'SwiftASWFDemo'
version = '1.0.0'
category = 'public.app-category.graphics-design'

[apps.SwiftASWFDemo.plist]
commit = '$(COMMIT_HASH)'

[apps.MXGraphEditor]
identifier = 'io.athem.MXGraphEditor'
product = 'MXGraphEditor'
version = '1.0.0'
category = 'public.app-category.graphics-design'

[apps.MXGraphEditor.plist]
commit = '$(COMMIT_HASH)'
